export { default as Navigation } from "./Navigation";
export { default as LanguageSwitcher } from './LanguageSwitcher';
export { default as Intro } from "./Intro";
export { default as Greeting } from './Greeting';
export { default as About } from "./About";
export { default as Sidebar } from "./Sidebar";
export { default as Projects } from "./Projects";
export { default as Contact } from "./Contact";
export { default as Footer } from "./Footer";
export { default as FrequencyBars } from './FrequencyBars';
export { default as SpotifyVinyl} from './SpotifyVinyl';
export { default as ScrollIndicator } from './ScrollIndicator';
export { default as SkillConstellation } from './SkillConstellation';
